### PR TITLE
Update AnimationManager.cpp

### PR DESCRIPTION
**Pull request by uoitalia**
fixes animations on mul files with high details, this was already fixed on classicuo side, AND uofiddler https://github.com/uoitalia/UOFiddler

### CODE REVIEW

**Comment by fungos** [comment]
Great! I've just started refactoring a bit the  code dealing with data,  good timing. Can you explain what is happening there? :)

**Comment by uoitalia** [comment]
uh?! yes, the extracted index data from anim3.mul/idx is wrong, as you can see here:
image
while, with the fix, you will see, in the game, the correct animation as in UOFiddler:
image

**Comment by uoitalia** [comment]
If you're wondering HOW we found out this, it was only a mere fortunate case, I've checked some uncorrect or missing monster animation in the CUO client and UOFiddler, and found out an animation EDITOR that was able to show them: http://uoanim.sourceforge.net/

After that, I've made the uofiddler patch and Andrea Angelini made the patch to classicuo client itself.

**Comment by fungos** [comment]
Awesome! Thanks for taking the time to explain it and thanks a lot for caring and contributing!

**Comment by Nirad** [comment]
yes that's fix some animations problem but on bodies cause a big big frame drop
capture d ecran 2019-03-01 a 19 17 47

**Comment by Nirad** [comment]
After more testing the frame drop is more related to debug and logging nice one ! I am running on UOP file format right now.
capture d ecran 2019-03-01 a 20 00 15

**Comment by Nirad** [comment]
and bring back the mount height offset Bug.
capture d ecran 2019-03-01 a 20 05 59

**Pull request merged**
