### PR TITLE
Object handlers fix corpse

### PR DESCRIPTION
**Pull request by Nirad**
for issues #4 
Original Client
image

CrossUO:
image

### CODE REVIEW

**Comment by fungos** [comment]
Good one, but I think before merging we can do two improvements:
- Add an option in the menu to disable showing on corpses, as it is useful. But as we target parity, the default is show corpses.
- Fix the position, there are two issues in the positioning there. Over characters head and over the corpse.

**Comment by Nirad** [comment]
ok i will work on this !

**Comment by Nirad** [comment]
CrossUO:
capture d ecran 2019-02-21 a 20 03 45

**Comment by Nirad** [comment]
capture d ecran 2019-02-21 a 21 09 01

**Pull request merged**
